### ISSUE TITLE
QWERTY ⌘

### ISSUE THREAD

**Issue by ghost** [maxadamski/polski-dvp#2]
Czy jest możliwość ustawienia klawiatury tak, żeby wciśnięcie klawiszy specjalnych innych niż niezbędny dla polskich znaków option (⌥) przywracało tymczasowo układ QWERTY w ten sam sposób, jak to się dzieje w układzie _Dvorak QWERTY ⌘_ (wbudowanym w MacOS)?

**Comment by maxadamski** [comment]
Tak. Musisz w Ukelele (do ściągnięcia przez `brew cask`) edytować `polski-dvp.keylayout` i dla każdej kombinacji klawiszy specjalnych ustaw klawisze tak jak chcesz.

Aktualnie ten układ nie ma specjalnego zachowania na ⌘, więc w Ukelele trzeba dodać nowy `Keyboard Map` dla ⌘, shift+⌘, caps+⌘ i shift+caps+⌘. W Twoim przypadku:
- ⌘ zmienia układ na małe litery QWERTY
- shift+⌘ i caps+⌘ na wielkie litery QWERTY
- shift+caps+⌘ na _małe_ litery QWERTY

Na koniec zapisz nowy `.bundle`, `.keylayout` i przenieś ten `.bundle` do `'/Library/Keyboard Layouts/'`. Fajnie by było, jakbyś jeszcze zrobił pull requesta. Może komuś się przyda ;).

Tak by the way, to jest sporo klikania, więc przetestuj sobie na początek, czy sam ⌘ działa, a shifty uzupełnij później.
